name: Check and Alert Prices of Your desired product
on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-price:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install requests beautifulsoup4
        
      - name: Create config file
        run: |
          echo '{
            "email": {
              "sender_email": "${{ secrets.SENDER_EMAIL }}",
              "sender_name": "${{ secrets.SENDER_NAME || 'Price Tracker' }}",
              "api_key": "${{ secrets.BREVO_API_KEY }}",
              "recipient_email": "${{ secrets.RECIPIENT_EMAIL }}"
            },
            "price": {
              "last_price": ${{ vars.LAST_PRICE || 1399.0 }},
              "last_checked": null,
              "original_price": 1989.0
            },
            "check_interval": 21600
          }' > price_config.json
          
      - name: Run price tracker
        run: python price_tracker.py --once
        env:
          PRODUCT_URLS: ${{ secrets.PRODUCT_URLS }}
          PRODUCT_NAME: ${{ secrets.PRODUCT_NAME }}

      - name: Run price tracker
        id: price_check
        run: |
          python price_tracker.py --once
          if grep -q "Price drop detected\|Price increased" price_tracker.log; then
            echo "price_changed=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Update last price variable
        if: steps.price_check.outputs.price_changed == 'true'
        run: |
          current_price=$(cat price_config.json | jq -r '.price.last_price')
          curl -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/LAST_PRICE \
            -d "{\"name\":\"LAST_PRICE\",\"value\":\"${current_price}\"}"
        shell: bash
